name: Gradle Cache Maker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: Setup Gradle Wrapper Cache
      - name: Build
        run: ./gradlew assemble --stacktrace --no-daemon
