name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: Setup Gradle Wrapper Cache
      - name: Build and Copy JS
        run: ./gradlew assemble --stacktrace
      - shell: bash
        name: "Commit changes back to PR"
        run: |
          git config --global user.email "automation@example.notARealEmail"
          git config --global user.name "Automation McBotterson"
          git add .
          git commit -m "ci(dist): updating dist code [AUTO-258]"
          git push -u origin $(git rev-parse --abbrev-ref HEAD)
